/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2026 Galih Tama <galpt@v.recipes>
 *
 * This software may be used and distributed according to the terms of the GNU
 * General Public License version 2.
 */
#ifndef __INTF_H
#define __INTF_H

/*
 * Shared BPF constants for scx_flow.
 */
enum consts {
	NSEC_PER_USEC = 1000ULL,
	NSEC_PER_MSEC = (1000ULL * NSEC_PER_USEC),

	FLOW_SLICE_MIN_NS = (50ULL * NSEC_PER_USEC),
	FLOW_SLICE_RESERVED_MAX_NS = (250ULL * NSEC_PER_USEC),
	FLOW_SLICE_RESERVED_TUNE_MAX_NS = (350ULL * NSEC_PER_USEC),
	FLOW_SLICE_SHARED_NS = (1ULL * NSEC_PER_MSEC),
	FLOW_SLICE_SHARED_MIN_NS = (750ULL * NSEC_PER_USEC),
	FLOW_SLICE_SHARED_MAX_NS = (1500ULL * NSEC_PER_USEC),
	FLOW_SLICE_CONTAINED_MIN_NS = (1200ULL * NSEC_PER_USEC),
	FLOW_BUDGET_MAX_NS = (2ULL * NSEC_PER_MSEC),
	FLOW_BUDGET_MIN_NS = (500ULL * NSEC_PER_USEC),
	FLOW_SLEEP_MAX_NS = (250ULL * NSEC_PER_MSEC),
	FLOW_INTERACTIVE_SLEEP_MIN_NS = (750ULL * NSEC_PER_USEC),
	FLOW_INTERACTIVE_FLOOR_NS = (100ULL * NSEC_PER_USEC),
	FLOW_INTERACTIVE_FLOOR_MIN_NS = (80ULL * NSEC_PER_USEC),
	FLOW_INTERACTIVE_FLOOR_MAX_NS = (200ULL * NSEC_PER_USEC),
	FLOW_PREEMPT_BUDGET_MIN_NS = (150ULL * NSEC_PER_USEC),
	FLOW_PREEMPT_BUDGET_MAX_NS = (350ULL * NSEC_PER_USEC),
	FLOW_PREEMPT_REFILL_MIN_NS = (200ULL * NSEC_PER_USEC),
	FLOW_PREEMPT_REFILL_MAX_NS = (350ULL * NSEC_PER_USEC),
	FLOW_RT_WAKE_SLICE_NS = (50ULL * NSEC_PER_USEC),
	FLOW_LATENCY_LANE_REFILL_MIN_NS = (60ULL * NSEC_PER_USEC),
	FLOW_LATENCY_LANE_BUDGET_MIN_NS = (80ULL * NSEC_PER_USEC),
	FLOW_LATENCY_CREDIT_GRANT_MIN = 1ULL,
	FLOW_LATENCY_CREDIT_GRANT_MAX = 4ULL,
	FLOW_LATENCY_CREDIT_MAX = 4ULL,
	FLOW_LATENCY_CREDIT_GRANT = 2ULL,
	FLOW_LATENCY_CREDIT_DECAY_MIN = 1ULL,
	FLOW_LATENCY_CREDIT_DECAY_MAX = 4ULL,
	FLOW_LATENCY_CREDIT_DECAY = 1ULL,
	FLOW_LATENCY_DEBT_MAX = 4ULL,
	FLOW_LATENCY_DEBT_URGENT_MIN_MIN = 1ULL,
	FLOW_LATENCY_DEBT_URGENT_MIN_MAX = 3ULL,
	FLOW_LATENCY_DEBT_URGENT_MIN = 1ULL,
	FLOW_LATENCY_DEBT_RAISE_STEP = 1ULL,
	FLOW_LATENCY_DEBT_DECAY_STEP = 1ULL,
	FLOW_URGENT_LATENCY_BURST_MIN = 1ULL,
	FLOW_URGENT_LATENCY_BURST_MAX_TUNE = 4ULL,
	FLOW_URGENT_LATENCY_BURST_MAX = 2ULL,
	FLOW_RESERVED_QUOTA_BURST_MIN = 2ULL,
	FLOW_RESERVED_QUOTA_BURST_MAX_TUNE = 8ULL,
	FLOW_RESERVED_QUOTA_BURST_MAX = 4ULL,
	FLOW_RESERVED_LANE_BURST_MIN = 2ULL,
	FLOW_RESERVED_LANE_BURST_MAX_TUNE = 10ULL,
	FLOW_RESERVED_LANE_BURST_MAX = 5ULL,
	FLOW_STABLE_SCORE_MAX = 8ULL,
	FLOW_STABLE_LOCAL_SCORE_MIN = 3ULL,
	FLOW_STABLE_LOCAL_NR_RUNNING_MAX = 2ULL,
	FLOW_STABLE_SCORE_GAIN = 1ULL,
	FLOW_STABLE_SCORE_DECAY = 2ULL,
	FLOW_STABLE_MISMATCH_DECAY = 1ULL,
	FLOW_LOCAL_FAST_NR_RUNNING_MIN = 1ULL,
	FLOW_LOCAL_FAST_NR_RUNNING_MAX_TUNE = 6ULL,
	FLOW_LOCAL_FAST_NR_RUNNING_MAX = 4ULL,
	FLOW_LOCAL_RESERVED_BURST_MIN = 2ULL,
	FLOW_LOCAL_RESERVED_BURST_MAX_TUNE = 8ULL,
	FLOW_LOCAL_RESERVED_BURST_MAX = 5ULL,
	FLOW_CONTAINED_STARVATION_MIN = 3ULL,
	FLOW_CONTAINED_STARVATION_MAX_TUNE = 12ULL,
	FLOW_CONTAINED_STARVATION_MAX = 6ULL,
	FLOW_SHARED_STARVATION_MIN = 6ULL,
	FLOW_SHARED_STARVATION_MAX_TUNE = 20ULL,
	FLOW_SHARED_STARVATION_MAX = 12ULL,
	FLOW_HOG_SCORE_MAX = 8ULL,
	FLOW_HOG_SCORE_CONTAIN = 3ULL,
	FLOW_HOG_SCORE_EXHAUST_STEP = 2ULL,
	FLOW_HOG_SCORE_DECAY_STEP = 1ULL,
	FLOW_HOG_RECOVERY_MARGIN_NS = (50ULL * NSEC_PER_USEC),
	FLOW_REFILL_DIV = 100ULL,
};

#ifndef __VMLINUX_H__
typedef unsigned char u8;
typedef unsigned short u16;
typedef unsigned int u32;
typedef unsigned long u64;

typedef signed char s8;
typedef signed short s16;
typedef signed int s32;
typedef signed long s64;

typedef int pid_t;
#endif /* __VMLINUX_H__ */

struct flow_cpu_state {
	u64 urgent_latency_burst_rounds;
	u64 high_priority_burst_rounds;
	u64 local_reserved_burst_rounds;
	u64 reserved_lane_burst_rounds;
	u64 contained_starvation_rounds;
	u64 shared_starvation_rounds;
};

#endif /* __INTF_H */
