/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Define struct scx_enums that stores the load-time values of enums
 * used by the BPF program.
 *
 * Copyright (c) 2024 Meta Platforms, Inc. and affiliates.
 */

#ifndef __SCX_ENUMS_H
#define __SCX_ENUMS_H

struct scx_enums {
	u64 SCX_OPS_NAME_LEN;
	u64 SCX_SLICE_DFL;
	u64 SCX_SLICE_INF;

	u64 SCX_DSQ_FLAG_BUILTIN;
	u64 SCX_DSQ_FLAG_LOCAL_ON;
	u64 SCX_DSQ_INVALID;
	u64 SCX_DSQ_GLOBAL;
	u64 SCX_DSQ_LOCAL;
	u64 SCX_DSQ_LOCAL_ON;
	u64 SCX_DSQ_LOCAL_CPU_MASK;

	u64 SCX_TASK_QUEUED;
	u64 SCX_TASK_RESET_RUNNABLE_AT;
	u64 SCX_TASK_DEQD_FOR_SLEEP;
	u64 SCX_TASK_STATE_SHIFT;
	u64 SCX_TASK_STATE_BITS;
	u64 SCX_TASK_STATE_MASK;
	u64 SCX_TASK_CURSOR;

	u64 SCX_TASK_NONE;
	u64 SCX_TASK_INIT;
	u64 SCX_TASK_READY;
	u64 SCX_TASK_ENABLED;
	u64 SCX_TASK_NR_STATES;

	u64 SCX_TASK_DSQ_ON_PRIQ;

	u64 SCX_KICK_IDLE;
	u64 SCX_KICK_PREEMPT;
	u64 SCX_KICK_WAIT;

	u64 SCX_ENQ_WAKEUP;
	u64 SCX_ENQ_HEAD;
	u64 SCX_ENQ_CPU_SELECTED;
	u64 SCX_ENQ_PREEMPT;
	u64 SCX_ENQ_REENQ;
	u64 SCX_ENQ_LAST;
	u64 SCX_ENQ_CLEAR_OPSS;
	u64 SCX_ENQ_DSQ_PRIQ;
};

#endif /* __SCX_ENUMS_H */
