//! sched_ext struct_ops type definitions.
//!
//! The `sched_ext_ops` struct field names must match kernel BTF exactly.
//! Field types don't matter for BTF — the userspace loader handles the
//! type mapping. The trampolines are now generated by the `scx_ops_define!`
//! proc macro in `scx-ebpf-derive`.

// ── Callback type aliases ───────────────────────────────────────────────
//
// Generic function pointer types for struct field declarations. The
// actual signatures don't matter for BTF (they get patched), but they
// must be pointer-sized so Option<T> uses null-pointer optimization.

type VoidCb = unsafe extern "C" fn(*const u64);
type I32Cb = unsafe extern "C" fn(*const u64) -> i32;
type InitCb = unsafe extern "C" fn() -> i32;

// ── sched_ext_ops ───────────────────────────────────────────────────────

/// Kernel `struct sched_ext_ops` — 34 callback fields + 6 data fields.
#[repr(C)]
pub struct sched_ext_ops {
    pub select_cpu: Option<I32Cb>,
    pub enqueue: Option<VoidCb>,
    pub dequeue: Option<VoidCb>,
    pub dispatch: Option<VoidCb>,
    pub tick: Option<VoidCb>,
    pub runnable: Option<VoidCb>,
    pub running: Option<VoidCb>,
    pub stopping: Option<VoidCb>,
    pub quiescent: Option<VoidCb>,
    pub r#yield: Option<VoidCb>,
    pub core_sched_before: Option<VoidCb>,
    pub set_weight: Option<VoidCb>,
    pub set_cpumask: Option<VoidCb>,
    pub update_idle: Option<VoidCb>,
    pub cpu_acquire: Option<VoidCb>,
    pub cpu_release: Option<VoidCb>,
    pub init_task: Option<I32Cb>,
    pub exit_task: Option<VoidCb>,
    pub enable: Option<VoidCb>,
    pub disable: Option<VoidCb>,
    pub dump: Option<VoidCb>,
    pub dump_cpu: Option<VoidCb>,
    pub dump_task: Option<VoidCb>,
    pub cgroup_init: Option<I32Cb>,
    pub cgroup_exit: Option<VoidCb>,
    pub cgroup_prep_move: Option<I32Cb>,
    pub cgroup_move: Option<VoidCb>,
    pub cgroup_cancel_move: Option<VoidCb>,
    pub cgroup_set_weight: Option<VoidCb>,
    pub cgroup_set_bandwidth: Option<VoidCb>,
    pub cpu_online: Option<VoidCb>,
    pub cpu_offline: Option<VoidCb>,
    pub init: Option<InitCb>,
    pub exit: Option<VoidCb>,
    // Data fields
    pub dispatch_max_batch: u32,
    pub flags: u64,
    pub timeout_ms: u32,
    pub exit_dump_len: u32,
    pub hotplug_seq: u64,
    pub name: [u8; 128],
}

/// All callbacks unset, all data fields zeroed.
pub const DEFAULT_OPS: sched_ext_ops = sched_ext_ops {
    select_cpu: None,
    enqueue: None,
    dequeue: None,
    dispatch: None,
    tick: None,
    runnable: None,
    running: None,
    stopping: None,
    quiescent: None,
    r#yield: None,
    core_sched_before: None,
    set_weight: None,
    set_cpumask: None,
    update_idle: None,
    cpu_acquire: None,
    cpu_release: None,
    init_task: None,
    exit_task: None,
    enable: None,
    disable: None,
    dump: None,
    dump_cpu: None,
    dump_task: None,
    cgroup_init: None,
    cgroup_exit: None,
    cgroup_prep_move: None,
    cgroup_move: None,
    cgroup_cancel_move: None,
    cgroup_set_weight: None,
    cgroup_set_bandwidth: None,
    cpu_online: None,
    cpu_offline: None,
    init: None,
    exit: None,
    dispatch_max_batch: 0,
    flags: 0,
    timeout_ms: 0,
    exit_dump_len: 0,
    hotplug_seq: 0,
    name: [0u8; 128],
};
