// SPDX-License-Identifier: GPL-2.0
//
// Author: Timon Stipkovits <timon2201@gmail.com>
//
// This software may be used and distributed according to the terms of the
// GNU General Public License version 2.

#ifndef DEFINES_H
#define DEFINES_H

#define SCHED_MODE_DSQ_PER_LLC 0
#define SCHED_MODE_DSQ_PER_CPU 1

#define NS_PER_US 1000ULL
#define NS_PER_MS 1000ULL * NS_PER_US

#define SLICE_LC (200 * NS_PER_US)
#define SLICE_INTERACTIVE (500 * NS_PER_US)
#define SLICE_NORMAL (500 * NS_PER_US)
#define SLICE_BATCH (500 * NS_PER_US)
#define SLICE_GREEDY (500 * NS_PER_US)

#define RUNTIME_PRIO_BOUNDARY_LC (200 * NS_PER_US)
#define RUNTIME_PRIO_BOUNDARY_INTERACTIVE (500 * NS_PER_US)
#define RUNTIME_PRIO_BOUNDARY_NORMAL (2000 * NS_PER_US)
#define RUNTIME_PRIO_BOUNDARY_BATCH (8000 * NS_PER_US)

#define RUNTIME_THRESH_PERCENT 5LL

#define MAX_RT_PRIO 100

#define MIN_AVG_RUNTIME 50ULL
#define MAX_RUNTIME_PER_TASK (400 * NS_PER_MS)

#define HISTORIC_TASK_SAMPLES 4
#define AVG_RUNTIME_OVERRIDE_FACTOR 5

#define DSQ_TYPE_LC 1
#define DSQ_TYPE_INTERACTIVE 2
#define DSQ_TYPE_NORMAL 3
#define DSQ_TYPE_BATCH 4
#define DSQ_TYPE_GREEDY 5
#define DSQ_PRIO_QUEUE_AMOUNT 5
#define DSQ_TYPE_EMPTY 6

#define VLAG_PROMOTE_THRESH 2000000LL
#define VLAG_DEMOTE_THRESH -2000000LL

#define VLAG_MIN -6000000LL
#define VLAG_MAX 6000000LL
#define SLEEP_CREDIT_DIVISOR 1LL
#define MAX_CREDITABLE_SLEEP 2000000LL

#define DEFAULT_DSQ_LOCAL_ON 0xC000000000000000ULL

#define DSQ_CPU_QUEUE_BASE_LC 1536
#define DSQ_CPU_QUEUE_BASE_INTERACTIVE 2048
#define DSQ_CPU_QUEUE_BASE_NORMAL 2560
#define DSQ_CPU_QUEUE_BASE_BATCH 3072
#define DSQ_CPU_QUEUE_BASE_GREEDY 3584

#define DSQ_LLC_QUEUE_BASE_LC 4224
#define DSQ_LLC_QUEUE_BASE_INTERACTIVE 4288
#define DSQ_LLC_QUEUE_BASE_NORMAL 4352
#define DSQ_LLC_QUEUE_BASE_BATCH 4416
#define DSQ_LLC_QUEUE_BASE_GREEDY 4480

#define QUEUE_START DSQ_TYPE_GREEDY

#define AVG_RUNTIME_START (500 * NS_PER_US)

#define MAX_CPUS 512

#endif  // DEFINES_H
