#!/bin/bash

cd $1
rm -rf libbpf
git clone --depth=1 https://github.com/libbpf/libbpf
cd libbpf
git fetch --depth=1 origin $2
git checkout $2

# This is needed because we haven't built libbpf yet
# and this is where the headers will end up
mkdir src/usr
mkdir src/usr/include