name: install-deps

runs:
  using: 'composite'
  steps:
    - name: Install build dependencies
      run: |
        if sudo -n true 2>/dev/null; then
          sudo apt-get update -q
          sudo apt-get install -y -q libelf-dev pkg-config clang-19 llvm-19 \
            libzstd-dev protobuf-compiler libseccomp-dev libcap-ng-dev
        fi
        echo /usr/lib/llvm-19/bin >> $GITHUB_PATH
      shell: bash
