name: install-deps

runs:
  using: 'composite'
  steps:
    - name: Install build dependencies
      run: |
        if sudo -n true 2>/dev/null; then
          read -ra pkgs <<< "$SCX_PACKAGES"
          sudo apt-get update -qq
          sudo apt-get install -y -qq "${pkgs[@]}"
        fi
        echo /usr/lib/llvm-19/bin >> $GITHUB_PATH
      shell: bash
