name: install-deps

runs:
  using: 'composite'
  steps:
    ### OTHER REPOS ####
    # turn off interactive, refresh pkgs
    - run: |
        echo 'debconf debconf/frontend select Noninteractive' | sudo debconf-set-selections
        sudo rm /var/lib/man-db/auto-update
        sudo apt-get update -y
        sudo apt-get install -y tasksel
        sudo tasksel remove ubuntu-desktop
      shell: bash

    ### DOWNLOAD AND INSTALL DEPENDENCIES ###

    # Download dependencies packaged by Ubuntu
    - run: |
        sudo apt install -f -y bison busybox-static cmake coreutils \
        cpio elfutils file flex gcc gcc-multilib git iproute2 jq kbd kmod \
        libcap-dev libelf-dev libunwind-dev libvirt-clients libzstd-dev \
        linux-headers-generic linux-tools-common linux-tools-generic make \
        ninja-build pahole pkg-config python3-dev python3-pip python3-requests \
        qemu-kvm rsync stress-ng udev zstd libseccomp-dev libcap-ng-dev \
        llvm-19 clang-19 python3-full curl meson bpftrace dwarves rustup \
        protobuf-compiler

        echo /usr/lib/llvm-19/bin >> $GITHUB_PATH
      shell: bash

    # ensure some toolchain is installed
    - run: |
        rustup default nightly
      shell: bash

    # virtme-ng
    - run: sudo pip3 install virtme-ng --break-system-packages
      shell: bash

    # Setup KVM support
    - run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
      shell: bash

    ### END DEPENDENCIES ###
