[package]
name = "scx_framesched"
version = "0.0.1"
authors = ["David Vernet <void@manifault.com>"]
edition = "2021"
description = "A deadline scheduler designed for interactivity"
license = "GPL-2.0-only"

[dependencies]
anyhow = "1.0.65"
clap = { version = "4.1", features = ["derive", "env", "unicode", "wrap_help"] }
ctrlc = { version = "3.1", features = ["termination"] }
fb_procfs = "0.7.0"
libbpf-rs = "0.24.1"
libc = "0.2"
log = "0.4.17"
once_cell = "1.19.0"
ordered-float = "3.4.0"
plain = "0.2.3"
procfs = "0.17"
scx_utils = { path = "../../../rust/scx_utils", version = "1.0.1" }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
simplelog = "0.12.0"
sorted-vec = "0.8.3"
static_assertions = "1.1.0"
metrics = "0.23.0"
metrics-exporter-prometheus = "0.15.0"

[build-dependencies]
scx_utils = { path = "../../../rust/scx_utils", version = "1.0.1" }

[features]
enable_backtrace = []
